branches:
  only:
  - master
language: python
python:
- 2.7
install:
- pip install -r requirements.txt
script:
- export DEBUG=1
- fab build
notifications:
  email:
    on_success: always
    on_failure: always
before_install:
- openssl aes-256-cbc -K $encrypted_50f1188d362f_key -iv $encrypted_50f1188d362f_iv
  -in client_secret.json.enc -out client_secret.json -d
- git submodule sync
- git submodule update --init --recursive
after_success: bash deploy.sh
env:
  global:
  - secure: YDPqeERBwAFlFAaYf5LBaG6CZDPxSRsgP5HCAHv5kkAAtVdfp14Ly7EZV+8bSyUOaagE1kzcD1vUsJLAH7IIpPkoBA3IOgUd9UmqyDsfMk8iqqGXBKuB5/bf8b8zkKhM9ZQ0Rf054Hw4speg69Vrth+7jbR+9wjW9DV3UyzpG0w7tfjLlDgDkoUneYQDjMju7PykhKoOQxxVL6x8LFpkPrSZIOgs6F50XuTU9A7c97tQ1+YYQcK1LpeTHxQXtPvvGMhuG5xod/v5mHHUawtnDygHD0gVZ2QkA9pA0dV7+9LTDOWPS4zat3YIbsYoX1D5D0cvCpAHLy2z3TLnXdo/7zW9IW9FI69ZRnOvXkq/O8o0WHt28OeErWYOIwPV+Jgxcmd350Gf7Bo8O/yzKMZew8uqOx6QtX89FIrYbt3D7AwL92P/su22yo0sXh+/6TGHvcPxdVaQ92i62Y7EedCPDO1OyuQNvSqFeuuLQM2Au9ZVyUziivxR6TA1NVYuGlnBlBMApnPoO2xGc+Af5Bd8KKKXQg3twBQ4IaAbDUX7M6e3V1MZAOIf7wM/8/xYfFV69KEEGq6o3k7PXGP9oB6lsOeKCRZ8JDbM222hXVOLe9bhp3NxlG1AQzdsz1P93287ve9xYqnSnto/vXikh2gnt88/zpsQnKFGofbmvcsBtkk=
  - secure: rUtpfgib8dz+kNRszKXotv03krNsyHSTS/r2QmOvPYiHpkxYK9o+rL/nI/iC+Fm10nwrlJEC5rGnW/f//tlV7d9WtHxWVTuKAaUXCx83T06FyRlN4PkedvlMTZNj0ee8COOCI1hyhKZnhJW36R4933fBYV/92z0jZu6zmKgutSIyAJwRPaRJf7NOXJd8RvzNePzQsrblOf9uEkfs9/FyPrfGAmtt+gi/F6v8betRDgVd1oNY7zc0Ds9cVwuGm5yQQO4YNoOOqr2tlTHjm/J04NJdhJAj2dEk41VldtecjjqMnwcY97ssalOzBQ3oo3HFFbJUAVH3ClvZKZ3nwpXRvUmwjDCK9hwoTCRgO9x0kLLMWFkyit3/gN2v9N3z+hBAfahbC1VbXuoJS/+n2DNSPHRRlcSQonEsrLVyuZn/PsYzNJ32jqHONhAwIUppbJSU+7JuPA3TEKiPRQXgwMOZtqbSQKrk64VfPAuVAh1RtIWqjAam3JTavl2TXo3+2T3qLcSqBlResI5RX0MtFDdo5XmOVGckJaIWBaxbRNivbbh8h0ywLEIzYSM5H0EVzz/46PbPdiy04kM9IWD4uryY9QTgZJeuNeWoCmX4wnYo9Gb19A4HBn1//qUivMj6ByMjVztiK7fgq7eYLXFF8+XRteFSAlm2PjEBqDw2jKR5E1I=
